import { FIELD_RULES } from './lib/inspectionSafety.mjs'
export default function FieldVerification({ extraction, meta, onChange }) {
  const review = (field, change) => onChange('fieldReviews', { ...meta.fieldReviews, [field.id]: { state: 'unreviewed', ...meta.fieldReviews?.[field.id], ...change, value: field.value } })
  return <section className="evidence-verification"><h4>Verify against the physical label</h4><p>OCR agreement is a heuristic, not an accuracy probability. Confirm each decisive reading. “Not detected” is not proof that a declaration is absent. Correct the transcript above when needed; the original OCR remains separate.</p>
    {extraction.fields.filter((field) => FIELD_RULES[field.id]).map((field) => <div className="field-review-row" key={field.id}><label htmlFor={`verify-${field.id}`}>{field.label}<br /><b>{field.value || 'Not detected'}</b></label><select id={`verify-${field.id}`} value={meta.fieldReviews?.[field.id]?.state || 'unreviewed'} onChange={(event) => review(field, { state: event.target.value })}><option value="unreviewed">Needs verification</option><option value="confirmed" disabled={!field.detected}>Confirmed on label</option><option value="absent" disabled={field.detected}>Physically absent</option><option value="unreadable">Unreadable — retake</option><option value="not_captured">Panel not captured</option></select><input aria-label={`${field.label} verification note`} value={meta.fieldReviews?.[field.id]?.reason || ''} onChange={(event) => review(field, { reason: event.target.value })} placeholder="Source panel and evidence for this confirmation / absence" />{meta.fieldCandidates?.[field.id]?.length > 1 && <small role="status">Conflicting OCR readings: {meta.fieldCandidates[field.id].map((candidate) => `${candidate.value} [${candidate.sources.join(', ')}]`).join(' · ')}</small>}</div>)}
    <div className="safety-confirmations">{[
      ['allPanelsCaptured', 'I inspected all relevant package panels; an absent declaration was not merely outside the photograph.'],
      ['classificationConfirmed', 'I verified commodity class, category and exemption inputs against the actual package.'],
      ['pdpConfirmed', 'I verified the physical principal display panel area, not just the projected photo area.'],
      ['measurementConfirmed', 'I verified a same-plane physical scale and individual glyph measurements (not an OCR line box).'],
      ['widthCharacterConfirmed', 'I verified the measured character is subject to the width requirement, not an excepted narrow character.'],
    ].map(([id, label]) => <label key={id}><input type="checkbox" checked={Boolean(meta[id])} onChange={(event) => onChange(id, event.target.checked)} />{label}</label>)}<label>Measurement surface<select aria-label="Measurement surface" value={meta.measurementSurface || 'unverified'} onChange={(event) => onChange('measurementSurface', event.target.value)}><option value="unverified">Not verified</option><option value="flat">Flat, same plane</option><option value="curved">Curved — abstain from geometry verdict</option></select></label></div>
  </section>
}
