import { useState } from 'react'
import { ArrowRight, CircleHelp, ScanLine } from 'lucide-react'
import './inspectionCommand.css'
import InspectionInsights from './InspectionInsights.jsx'

const statusNames = { manual_review: 'Needs officer review', non_compliant: 'Flagged checks require attention', compliant: 'Encoded checks passed · officer-reviewed decision support', exempt: 'Exemption / scope review', awaiting_ocr: 'Photograph captured · read label fields next' }
function StackedEvidence({ data, total, label }) {
  return <div className="current-stacked-bar" role="img" aria-label={`${label}: ${data.map(item => `${item.label} ${item.count}`).join(', ')}; ${total} total.`}>
    {total ? data.filter(item => item.count > 0).map(item => <span key={item.id} style={{ width: `${item.count / total * 100}%`, background: item.color }} title={`${item.label}: ${item.count} of ${total}`}>{item.count}</span>) : <span className="no-chart-data">No assessed evidence yet</span>}
  </div>
}
export default function InspectionCommandView({ analysis, onInspect }) {
  const [filter, setFilter] = useState('all')
  if (!analysis?.hasEvidence) return <section className="inspection-command page-enter"><span className="eyebrow">COMMAND VIEW / CURRENT PACKAGE</span><h2>Start with a package, not a chart.</h2><p>Upload a label in New inspection. Its OCR readings, verification states and rule checks will populate this view—even before sealing. Previous records remain in Inspection history.</p><button className="primary-action fit" onClick={() => onInspect()}><ScanLine size={17} /> Inspect a package</button></section>
  const total = analysis.fields.length
  const selected = filter === 'all' ? analysis.fields : analysis.fields.filter(field => field.status === filter)
  return <section className="inspection-command page-enter" aria-label="Current inspection analysis">
    <header className="current-package-header"><div><span className="eyebrow">COMMAND VIEW / CURRENT PACKAGE</span><h2>{analysis.productName}</h2><code>{analysis.id}</code><p>{analysis.pendingRestore ? 'Saved draft · restore it to continue.' : analysis.saved ? 'Sealed inspection · retained until you start another package.' : 'Live unfinished inspection · updates as you capture, extract and verify.'}</p></div>{analysis.thumbnail && <img src={analysis.thumbnail} alt="Current package label" />}<button className="primary-action fit" onClick={() => onInspect()}>{analysis.pendingRestore ? 'Restore / continue inspection' : 'Return to inspection'}<ArrowRight size={17} /></button></header>
    <div className="current-assessment" role="status"><b>{analysis.running ? 'OCR / image processing in progress' : statusNames[analysis.status]}</b><span>{analysis.pendingPreview ? 'An OCR preview is pending; charts still describe the accepted working transcript.' : `${analysis.verified} of ${total} tracked readings verified. ${total - analysis.verified} need interpretation or review.`} {analysis.error && `Latest operation: ${analysis.error}`}</span></div>
    <div className="current-metrics"><article><span>Captured panels</span><b>{analysis.panels.length}</b><small>Real uploaded photographs</small></article><article><span>Readable declarations</span><b>{analysis.detected} / {total}</b><small>Detection coverage, not OCR accuracy</small></article><article><span>Officer-verified</span><b>{analysis.verified} / {total}</b><small>Explicit field confirmations</small></article><article><span>Flagged rule checks</span><b>{analysis.ruleDistribution.find(item => item.id === 'fail').count}</b><small>Not a statutory determination</small></article></div>
    <InspectionInsights analysis={analysis} onInspect={onInspect} />
    <article className="current-chart evidence-distribution"><header><div><span className="eyebrow">CURRENT WORKING EVIDENCE</span><h3>Evidence distribution</h3></div><button onClick={() => setFilter('all')}>Show all {total} fields</button></header><p>Color describes the evidence state, not whether the product is legally compliant. Select a category to see what needs attention.</p>
      <StackedEvidence data={analysis.distribution} total={total} label="Declaration evidence distribution" />
      <div className="current-legend">{analysis.distribution.map(item => <button key={item.id} aria-pressed={filter === item.id} onClick={() => setFilter(item.id)}><i style={{ background: item.color }} /><span>{item.label}<small>{item.detail}</small></span><b>{item.count}<small>{Math.round(item.count / total * 100)}%</small></b></button>)}</div>
      <p className="chart-footnote">Denominator: {total} tracked declarations. Some, such as origin, FSSAI licence or best-before, are profile-dependent. Missing OCR is never proof of absence. Historical OCR disagreements remain visible below.</p>
      <div className="current-field-table"><table><caption>{filter === 'all' ? 'All tracked fields' : analysis.distribution.find(item => item.id === filter)?.label} · {selected.length} field(s)</caption><thead><tr><th>Declaration</th><th>Working reading / source</th><th>What the officer should do</th></tr></thead><tbody>{selected.map(field => <tr key={field.id}><th scope="row">{field.label}<span className="evidence-state" style={{ color: analysis.distribution.find(item => item.id === field.status).color }}>{analysis.distribution.find(item => item.id === field.status).label}</span></th><td>{field.value || 'No resolved value'}{field.status === 'conflict' && <small>Competing observations: {field.alternatives.join(' / ')}</small>}<small>{field.panel}</small>{field.historicalDisagreement && <small>Earlier OCR passes disagree; compare raw history.</small>}</td><td>{field.reason}<button onClick={() => onInspect(field.id)}>Review this field →</button></td></tr>)}</tbody></table>{!selected.length && <p>No fields are in this category.</p>}</div>
    </article>
    <div className="current-chart-grid"><article className="current-chart"><header><h3>Captured-panel coverage</h3></header><p>Four suggested views help locate declarations. Assigned photo roles do not prove every declaration is visible.</p><div className="coverage-grid">{analysis.coverage.map(role => <div key={role.id} className={role.captured ? 'captured' : 'uncaptured'}><b>{role.captured ? '✓ Captured' : '○ Not assigned'}</b><span>{role.label}</span></div>)}</div><h4>Located declarations by photo</h4><p className="chart-footnote">Each bar starts at zero; maximum {total} tracked fields. OCR source matching is heuristic.</p>{analysis.panels.map(panel => <div className="panel-evidence-bar" key={panel.id}><span>Panel {panel.index} · {panel.name}</span><div><i style={{ width: `${panel.located / total * 100}%` }} /></div><b>{panel.located} / {total}</b><small>{panel.passes} raw OCR pass(es) retained{panel.quality === null ? '' : ` · image-quality heuristic ${panel.quality}/100, not recognition accuracy`}</small></div>)}</article>
    <article className="current-chart"><header><h3>Rule-check outcomes</h3></header><p>These checks use the current transcript, supplied context and measurement evidence. A field may feed more than one check.</p><StackedEvidence data={analysis.ruleDistribution} total={analysis.checks.length} label="Current rule-check outcomes" /><ul className="rule-outcome-list">{analysis.ruleDistribution.map(item => <li key={item.id}><i style={{ background: item.color }} /><span>{item.label}</span><b>{item.count}</b></li>)}</ul><details><summary>Explain {analysis.checks.length} rule checks</summary><ul className="rule-reasons">{analysis.checks.map(check => <li key={check.id}><b>{check.label} · {check.status}</b><span>{check.reason}</span></li>)}</ul></details><p className="chart-footnote"><CircleHelp size={14} /> Physical size, all-panel completeness and legal applicability still require officer input. No chart certifies the package.</p></article></div>
  </section>
}
